apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mentora-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dara-cod/mentoria_k8s
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mentoria
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      1312